# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfSRJBaPi2JlZoaIlR620R_2QDncEM8p
"""

import pandas as pd
from google.colab import files

# Load dataset
df = pd.read_csv("netflix_data")

# 1. Check missing values
print("Missing Values:")
print(df.isnull().sum())

# 2. Remove duplicates
df = df.drop_duplicates()

# 3. Clean column names
df.columns = (
    df.columns.str.strip()
              .str.lower()
              .str.replace(" ", "_")
)

# 4. Standardize text columns
for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

# 5. Convert date format
if 'date_added' in df.columns:
    df['date_added'] = pd.to_datetime(
        df['date_added'],
        errors='coerce'
    ).dt.strftime('%d-%m-%Y')

# 6. Save cleaned dataset
output_file = "netflix_data_cleaned.csv"
df.to_csv(output_file, index=False)

print(f"Cleaned dataset saved as: {output_file}")

# 7. Automatically download the file (Google Colab)
files.download(output_file)
