# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3suj4YLC8dACPF0Gowp2GUiK_BwJQA2
"""

import pandas as pd
from google.colab import files

# Load Dataset
df = pd.read_csv("netflix_data.csv")

# 1. Identify Missing Values
print("Missing Values:")
print(df.isnull().sum())

# Handle Missing Values
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Not Available')
df['country'] = df['country'].fillna('Unknown')

# 2. Remove Duplicate Rows
df = df.drop_duplicates()

# 3. Standardize Text Values
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.title()

# 4. Convert Date Format
if 'date_added' in df.columns:
    df['date_added'] = pd.to_datetime(
        df['date_added'],
        errors='coerce'
    )
    df['date_added'] = df['date_added'].dt.strftime('%d-%m-%Y')

# 5. Rename Column Headers
df.columns = (
    df.columns.str.strip()
              .str.lower()
              .str.replace(' ', '_')
)

# 6. Check and Fix Data Types
if 'release_year' in df.columns:
    df['release_year'] = pd.to_numeric(
        df['release_year'],
        errors='coerce'
    ).astype('Int64')

# 7. Save Cleaned Dataset
output_file = "netflix_data_cleaned.csv"
df.to_csv(output_file, index=False)

print(f"Cleaned dataset saved as: {output_file}")

# 8. Automatically Download the File
files.download(output_file)